[CmdletBinding()]
param(
    [ValidateSet('extract', 'generate', 'verify')]
    [string]$Mode = 'verify'
)

$firmwareRoot = Join-Path (Resolve-Path (Join-Path $PSScriptRoot '..')).Path 'sensor-biomassa\firmware\biomass-sensor'
$headerPath = Join-Path $firmwareRoot 'web_ui.h'
$htmlPath = Join-Path $firmwareRoot 'web\index.html'

function Get-HeaderHtml {
    $header = [System.IO.File]::ReadAllText($headerPath)
    $match = [regex]::Match($header, 'R"HTML\((?<html>[\s\S]*?)\)HTML";')
    if (-not $match.Success) { throw 'WEB_UI_HTML raw string not found.' }
    return $match.Groups['html'].Value
}

function Get-GeneratedHeader([string]$html) {
    if ($html.Contains(')HTML"')) { throw 'HTML contains the reserved raw-string delimiter.' }
    return @"
#pragma once

#include <pgmspace.h>

// Generated from web/index.html by tools/Sync-BiomassWebUi.ps1.
// Edit the HTML source and regenerate this header; do not edit this file directly.
static const char WEB_UI_HTML[] PROGMEM = R"HTML($html)HTML";
"@
}

switch ($Mode) {
    'extract' {
        $directory = Split-Path -Parent $htmlPath
        if (-not (Test-Path -LiteralPath $directory)) { New-Item -ItemType Directory -Path $directory | Out-Null }
        [System.IO.File]::WriteAllText($htmlPath, (Get-HeaderHtml), [System.Text.UTF8Encoding]::new($false))
        Write-Output "Extracted $htmlPath"
    }
    'generate' {
        if (-not (Test-Path -LiteralPath $htmlPath)) { throw "Missing $htmlPath" }
        $html = [System.IO.File]::ReadAllText($htmlPath)
        [System.IO.File]::WriteAllText($headerPath, (Get-GeneratedHeader $html), [System.Text.UTF8Encoding]::new($false))
        Write-Output "Generated $headerPath"
    }
    'verify' {
        if (-not (Test-Path -LiteralPath $htmlPath)) { throw "Missing $htmlPath" }
        $expected = Get-GeneratedHeader ([System.IO.File]::ReadAllText($htmlPath))
        $actual = [System.IO.File]::ReadAllText($headerPath)
        if ($actual -cne $expected) { throw 'web_ui.h is not synchronized with web/index.html.' }
        Write-Output 'Biomass web UI header is synchronized.'
    }
}
