using System.Reflection;
using System.Text.Json;
using TecnalHub.Services.KlaMapping;
using Xunit;

namespace TecnalHub.Tests;

public sealed class KlaMappingScientificTests
{
    private static readonly KlaAnchor[] SerratiaAnchors =
    [
        new(2, 800, 121.84), new(7, 800, 179.91), new(12, 800, 195.83),
        new(2, 500, 58.21), new(7, 500, 96.98), new(12, 500, 140.51),
        new(2, 200, 8.28), new(7, 200, 15.17), new(12, 200, 21.20),
    ];

    [Fact]
    public void Reference_surface_matches_scipy_values_and_normalized_derivatives()
    {
        var surface = new KlaMappingEngine().Reconstruct(ReferenceInput());
        var fixtures = new[]
        {
            new Probe(0.00, 0.00, 9.38799267848141, 0.56920149280903, 6.95909310044441),
            new Probe(0.25, 0.25, 42.65043678635517, 57.62765194720379, 141.49154463150836),
            new Probe(0.50, 0.50, 96.98609305367583, 78.70850256309832, 162.83122897443530),
            new Probe(0.75, 0.75, 159.57148724619745, 87.51918044146502, 163.66748176367187),
            new Probe(1.00, 1.00, 194.79766238115502, 0.73926979278257, 6.27042075463004),
            new Probe(0.25, 0.75, 116.54106776531663, 93.47484205750379, 157.66301869529775),
            new Probe(0.75, 0.25, 73.30222387478008, 72.38482149982072, 186.46862992073423),
        };

        var differences = new List<string>();
        foreach (var fixture in fixtures)
        {
            var actual = surface.EvaluateNormalized(fixture.Q, fixture.N);
            differences.Add($"({fixture.Q},{fixture.N}) actual={actual} " +
                            $"delta=({actual.Value - fixture.Value},{actual.Dq - fixture.Dq},{actual.Dn - fixture.Dn})");
            Assert.True(
                Math.Abs(actual.Value - fixture.Value) <= 0.25 &&
                Math.Abs(actual.Dq - fixture.Dq) <= 2.0 &&
                Math.Abs(actual.Dn - fixture.Dn) <= 2.0,
                string.Join(Environment.NewLine, differences));
        }

        Assert.InRange(Math.Abs(surface.Diagnostics.MinimumKlaPerHour - 9.387992678481409), 0, 0.25);
        Assert.InRange(Math.Abs(surface.Diagnostics.MaximumKlaPerHour - 194.79766238115502), 0, 0.25);
    }

    [Fact]
    public void Reference_path_is_low_to_high_and_allocates_with_endpoint_clamping()
    {
        var engine = new KlaMappingEngine();
        var surface = engine.Reconstruct(ReferenceInput());
        var path = engine.GeneratePath(surface, 0.59, 0.66);

        Assert.True(path.Count >= 10);
        Assert.True(path[0].KlaPerHour < path[^1].KlaPerHour);
        Assert.All(path, point =>
        {
            Assert.InRange(point.NormalizedAirflow, 0, 1);
            Assert.InRange(point.NormalizedAgitation, 0, 1);
            Assert.InRange(point.Headroom, 0, 0.5);
        });

        // Generated by the unmodified Python/SciPy paper pipeline (SciPy 1.17.1).
        Assert.InRange(path.Count, 26, 34);
        Assert.InRange(Math.Abs(path.Average(point => point.Headroom) - 0.1888975812776142), 0, 0.004);
        Assert.InRange(Math.Abs(path[0].NormalizedAirflow - 0.3344393697792826), 0, 0.015);
        Assert.InRange(Math.Abs(path[0].NormalizedAgitation), 0, 0.01);
        Assert.InRange(Math.Abs(path[0].KlaPerHour - 13.016620392167162), 0, 2.0);
        Assert.InRange(Math.Abs(path[^1].NormalizedAirflow - 0.7525210463230325), 0, 0.015);
        Assert.InRange(Math.Abs(path[^1].NormalizedAgitation - 1), 0, 0.01);
        Assert.InRange(Math.Abs(path[^1].KlaPerHour - 191.04438103356767), 0, 2.0);
    }

    [Fact]
    public void Candidate_search_uses_mean_normalized_boundary_headroom()
    {
        var engine = new KlaMappingEngine();
        var input = ReferenceInput() with
        {
            Algorithm = ReferenceInput().Algorithm with { CandidateGridResolution = 7 },
        };
        var result = engine.FindMaximumHeadroomPath(engine.Reconstruct(input));

        Assert.Equal(49, result.Diagnostics.CandidateCount);
        Assert.True(
            Math.Abs(result.Diagnostics.MeanHeadroom - 0.18284975261406144) <= 0.003,
            $"actual H={result.Diagnostics.MeanHeadroom:R}, " +
            $"start=({result.Diagnostics.SelectedStartAirflowNormalized:R}," +
            $"{result.Diagnostics.SelectedStartAgitationNormalized:R})");
        Assert.InRange(Math.Abs(result.Diagnostics.SelectedStartAirflowNormalized - 0.5), 0, 0.001);
        Assert.InRange(
            Math.Abs(result.Diagnostics.SelectedStartAgitationNormalized - 0.6666333333333333),
            0,
            0.001);
        Assert.Equal(result.Diagnostics.MeanHeadroom, result.Diagnostics.EvaluatedMaximumHeadroom, 12);
        Assert.True(result.Allocation.Count >= 2);
        Assert.True(result.Allocation.Zip(result.Allocation.Skip(1)).All(pair =>
            pair.First.KlaPerHour < pair.Second.KlaPerHour));

        var below = result.Allocate(double.NegativeInfinity);
        var above = result.Allocate(double.PositiveInfinity);
        Assert.Equal(result.Allocation[0], below);
        Assert.Equal(result.Allocation[^1], above);
    }

    [Fact]
    public void Full_reference_search_matches_embedded_current_scipy_oracle()
    {
        const string resourceName = "TecnalHub.Tests.fixtures.kla-reference-scipy.json";
        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceName);
        Assert.NotNull(stream);
        using var fixture = JsonDocument.Parse(stream);
        var root = fixture.RootElement;
        var generator = root.GetProperty("generator");
        Assert.Equal("1.17.1", generator.GetProperty("scipy").GetString());
        Assert.Equal("gradient_path_score.py", generator.GetProperty("paperScript").GetString());
        Assert.Equal(
            "a230fceeadfb08ba31b51c6c735fe70e5ff1e8fa0466b642ba2c0b23431385bf",
            generator.GetProperty("paperScriptSha256").GetString());
        Assert.Equal(150, root.GetProperty("settings").GetProperty("candidateGridResolution").GetInt32());

        var expected = root.GetProperty("bestPath");
        var expectedStart = expected.GetProperty("start");
        var expectedPoints = expected.GetProperty("points");
        var result = new KlaMappingEngine().FindMaximumHeadroomPath(
            new KlaMappingEngine().Reconstruct(ReferenceInput()));

        Assert.InRange(
            Math.Abs(result.Diagnostics.SelectedStartAirflowNormalized - expectedStart[0].GetDouble()),
            0,
            1e-10);
        Assert.InRange(
            Math.Abs(result.Diagnostics.SelectedStartAgitationNormalized - expectedStart[1].GetDouble()),
            0,
            1e-10);
        Assert.InRange(
            Math.Abs(result.Diagnostics.MeanHeadroom - expected.GetProperty("meanHeadroom").GetDouble()),
            0,
            1e-10);
        Assert.Equal(expected.GetProperty("count").GetInt32(), result.Diagnostics.AllocationSampleCount);

        var expectedFirst = expectedPoints[0];
        var expectedLast = expectedPoints[expectedPoints.GetArrayLength() - 1];
        Assert.InRange(Math.Abs(result.Path[0].NormalizedAirflow - expectedFirst.GetProperty("q").GetDouble()), 0, 1e-9);
        Assert.InRange(Math.Abs(result.Path[0].NormalizedAgitation - expectedFirst.GetProperty("n").GetDouble()), 0, 1e-9);
        Assert.InRange(Math.Abs(result.Path[0].KlaPerHour - expectedFirst.GetProperty("klaPerHour").GetDouble()), 0, 1e-8);
        Assert.InRange(Math.Abs(result.Path[^1].NormalizedAirflow - expectedLast.GetProperty("q").GetDouble()), 0, 1e-9);
        Assert.InRange(Math.Abs(result.Path[^1].NormalizedAgitation - expectedLast.GetProperty("n").GetDouble()), 0, 1e-9);
        Assert.InRange(Math.Abs(result.Path[^1].KlaPerHour - expectedLast.GetProperty("klaPerHour").GetDouble()), 0, 1e-8);
    }

    [Fact]
    public void Validation_refuses_duplicate_or_collinear_designs()
    {
        var engine = new KlaMappingEngine();
        var duplicate = ReferenceInput() with
        {
            Anchors = [.. SerratiaAnchors, SerratiaAnchors[0]],
        };
        Assert.Contains(engine.Validate(duplicate), issue => issue.Contains("repetidas", StringComparison.Ordinal));

        var collinear = ReferenceInput() with
        {
            Anchors =
            [
                new(2, 200, 1), new(4, 320, 2), new(6, 440, 3),
                new(8, 560, 4), new(10, 680, 5), new(12, 800, 6),
            ],
        };
        Assert.Contains(engine.Validate(collinear), issue => issue.Contains("colineares", StringComparison.Ordinal));
    }

    [Fact]
    public void Validation_refuses_non_finite_or_incoherent_numerical_parameters()
    {
        var engine = new KlaMappingEngine();
        var invalid = ReferenceInput() with
        {
            Algorithm = new KlaAlgorithmSettings
            {
                CloughTocherGradientTolerance = double.NaN,
                CandidateMinimum = double.NaN,
                OdeMaximumStep = 20,
                IntegrationHorizon = 10,
            },
        };

        var issues = engine.Validate(invalid);
        Assert.Contains(issues, issue => issue.Contains("Clough", StringComparison.Ordinal));
        Assert.Contains(issues, issue => issue.Contains("limites normalizados", StringComparison.Ordinal));
        Assert.Contains(issues, issue => issue.Contains("horizonte", StringComparison.Ordinal));
    }

    [Fact]
    public void Anchor_rows_support_proper_numerical_sorting()
    {
        var row50 = new TecnalHub.ViewModels.KlaAnchorRowViewModel { Agitation = "50", Airflow = "2.0", Kla = "10" };
        var row400 = new TecnalHub.ViewModels.KlaAnchorRowViewModel { Agitation = "400", Airflow = "2.0", Kla = "20" };
        var row750 = new TecnalHub.ViewModels.KlaAnchorRowViewModel { Agitation = "750", Airflow = "2.0", Kla = "30" };

        Assert.Equal(50, row50.AgitationValue);
        Assert.Equal(400, row400.AgitationValue);
        Assert.Equal(750, row750.AgitationValue);

        var list = new List<TecnalHub.ViewModels.KlaAnchorRowViewModel> { row400, row750, row50 };
        var sorted = list.OrderBy(r => r.AgitationValue).ToList();

        Assert.Same(row50, sorted[0]);
        Assert.Same(row400, sorted[1]);
        Assert.Same(row750, sorted[2]);
    }

    private static KlaExperimentSnapshot ReferenceInput() => new()
    {
        Name = "fixture only",
        Domain = new KlaDomain(2, 12, 200, 800),
        Anchors = SerratiaAnchors,
    };

    private sealed record Probe(double Q, double N, double Value, double Dq, double Dn);
}

